export const REQUEST_DATA = "REQUEST_DATA";
export const RECEIVE_DATA = "RECEIVE_DATA";

export const RECEIVED_ERROR = "RECEIVED_ERROR";

export const INCREASE_LIMIT = "INCREASE_LIMIT";
export const FETCHING_MORE = "FETCHING_MORE";

export const REQUEST_DETAILS = "REQUEST_DETAILS";
export const RECEIVE_DETAILS = "RECEIVE_DETAILS";
